const hex_seeds = [{
    name: '乾 QIAN',
    composition: '111111',
    aspect: 'CREATIVE POWER',
    guidance: 'Creative Power brings exception progress. There is an advantage in correct persistence',
    wisdom: 'The movement of the cosmos is in complete power. An enlightened person, therefore, works steadily to exert his will',
    art: '',
    upper: 4,
    lower: 4,
    first: "This line suggests that even in humble beginnings or minor positions, there is potential for greatness. It encourages patience, attention to small details, and a strong foundation to ensure future success.",
    second: "This line represents the need for correct behavior and staying true to one's principles. It suggests that through integrity and inner strength, one will find support and gain respect from others.",
    third: "This line indicates a time of difficulty or obstruction. It suggests that one may be in a position of power but is facing challenges. The advice here is to remain steadfast and avoid rash actions or overconfidence.",
    fourth: "This line signifies an opportunity for progress. It indicates that with determination and a clear sense of direction, obstacles can be overcome. The support of a wise or influential person may also be beneficial.",
    fifth: "This line symbolizes a strong leader or influential figure. It suggests that through virtue, humility, and leading by example, one will achieve success and attract loyal followers.",
    sixth: "This line warns of potential excess. It suggests that one has reached the limits of the situation or their power. It is a reminder to stay grounded, avoid arrogance, and understand when it is time to step back or make a change.",
    all: "You have become distinguished and live in harmony, the gate has been opened which will allow you to influence the world.",
},
{
    name: '坤 KUN',
    composition: '000000',
    aspect: 'RECEPTIVENESS',
    guidance: 'An enlightened person with a goal in mind at first becomes ocnfused; then he finds a leader. It is advantageous to find companions in the southwest (recepitve) and forego those in the northeast (immobile). Calm and correct persistence brings good fortune',
    wisdom: 'The powerful influence of receptivity (earth) forms teh condition for natural response. An enlightened person, therefore, uses moral excellence to support the outside world',
    art: '',
    upper: 2,
    lower: 2,
    first: "The first line suggests the need for persistence and hard work in the face of initial difficulties. It indicates that humble beginnings, if approached with dedication, can lead to success.",
    second: "This line represents the importance of being in the right place at the right time. It implies that alignment with the natural flow of events will bring progress and good fortune.",
    third: "The third line warns against stubbornness and the refusal to accept help or advice. It suggests that such attitudes can lead to misfortune and emphasizes the need for flexibility.",
    fourth: "This line indicates a time of potential growth and transformation. It suggests that if one is open to change and willing to let go of old patterns, progress can be made.",
    fifth: "The fifth line symbolizes a position of power and influence. It advises that with great power comes the responsibility to lead with virtue and wisdom, impacting others positively.",
    sixth: "The sixth line warns of potential excess and the dangers of overreach. It suggests that going beyond one's natural limits can lead to misfortune and emphasizes the importance of knowing one's boundaries.",
    all: "Your power grows in tune with your devotion to your vision. Weather the storm and you will have your desires.",
},
{
    name: '屯 ZHUN',
    composition: '100010',
    aspect: 'DIFFICULT BEGINNINGS',
    guidance: 'Difficult Beginnings result in exceptional progress. There is some advantage in correct persistence, but far-reaching goals should not be pursued. It is advantageous to develop supporters.',
    wisdom: 'Profound activity (clouds and thunder) forms the condition for Difficult Beginnings. An enlightened person, therefore, is concerned with the principles and policies of organization',
    art: '',
    upper: 5,
    lower: 7,
    first: "The first line suggests that while there may be potential for growth, it's important to address foundational issues first. Acting hastily without proper preparation could lead to difficulties.",
    second: "This line indicates progress despite minor setbacks. It symbolizes the importance of perseverance and maintaining a positive attitude in the face of minor obstacles.",
    third: "The third line warns against overreaching or forcing progress. It suggests that trying to rush or push too hard can lead to complications or failure.",
    fourth: "This line suggests the emergence of a beneficial opportunity, possibly through the support or advice of others. It's a time to be open to help and ready to act on good advice.",
    fifth: "The fifth line indicates a strong position and the potential for success. However, it advises to proceed with caution and wisdom, ensuring that actions are just and correct.",
    sixth: "The sixth line warns of potential dangers or failure if one continues on the current path. It advises reassessment of one's direction and possibly retreating or changing course to avoid negative outcomes.",
    all: "",
},
{
    name: '蒙 MENG',
    composition: '010001',
    aspect: 'INEXPERIENCE',
    guidance: 'Inexperience brings progress. It is not I who seeks the inexperienced. It is the inexperienced who seeks me. At the first divination I inform him, but if he asks repeatedly it is rude and annoying. As a rule, I do not inform the rude and annoying. There is, however, some advantage to correct persistence',
    wisdom: 'The difficult (spring) collects at the foot of the tranquil (mountain) forming the condition for Inexperience. An enlightened person, therefore, cultivates his chracter through decisive conduct.',
    art: '',
    upper: 6,
    lower: 5,
    first: "The first line suggests that there is a need for further learning and self-cultivation. It's a time to acknowledge one's limitations and seek knowledge humbly.",
    second: "This line indicates that one is on the correct path of learning and self-improvement. Persistence in pursuit of knowledge and wisdom will bring good fortune.",
    third: "The third line warns against arrogance and the refusal to accept guidance. It suggests that overconfidence in one's own knowledge can lead to mistakes and misfortune.",
    fourth: "This line suggests a period of growth and enlightenment. The willingness to learn from others and the environment leads to progress and success.",
    fifth: "The fifth line indicates maturity in learning and understanding. It suggests that one's wisdom and knowledge can be a source of guidance and benefit to others.",
    sixth: "The sixth line warns of the dangers of being trapped in ignorance or refusing to grow. It suggests that one must break free from old patterns and be open to continuous learning and self-improvement.",
    all: "",
},
{
    name: '需 XU',
    composition: '111010',
    aspect: 'CALCULATED WAITED',
    guidance: 'Calculated Waiting with a confident attitude will bring radiant progress. Correct persistence brings good fortune. It is advantageous to experience the collective flow.',
    wisdom: 'The anxious (clouds) rises up into the light of day (heaven) forming the condition for Calculated Waiting. An enlightened person, therefore, eats and drinks in comfort and contentment',
    art: '',
    upper: 5,
    lower: 4,
    first: "The first line suggests that patience and cautiousness are needed. It’s a time to address your situation calmly and not rush into action.",
    second: "This line indicates that there is potential for progress. Assistance may come from a sincere and trustworthy person.",
    third: "The third line warns of potential difficulties ahead. It suggests that one should be cautious and not undertake risky ventures or act impulsively.",
    fourth: "This line suggests that a period of waiting and preparation is coming to an end. It's time to emerge and take action, as success is within reach.",
    fifth: "The fifth line indicates a position of strength and influence. It suggests that through patience and integrity, one will attract support and achieve success.",
    sixth: "The sixth line warns against overconfidence or pushing too hard. It advises that the time for action has passed, and one should be content with the achievements made.",
    all: "",
},
{
    name: '訟 SONG',
    composition: '010111',
    aspect: 'CONFLICT',
    guidance: 'Conflict. Confidence is accompanied by obstacles. A cautiuos yieldinig brings good fortune. Continuing to the end brings misfortune. It is advantageous to see the leader. There is no advatange in experiencing the collective flow.',
    wisdom: 'The strong (heaven) and the difficulty (water) go their opposite ways forming the condition for Conflict. An enlightened person therefore in performing his functions, carefully plans the beginning.',
    art: '',
    upper: 4,
    lower: 5,
    first: "The first line suggests that conflict can be avoided by maintaining a humble and sincere attitude. It’s important to recognize when to retreat and avoid unnecessary disputes.",
    second: "This line indicates that one is in a position to influence the situation positively. By taking a firm yet measured approach, conflict can be resolved.",
    third: "The third line warns against engaging in conflict impulsively. It suggests that rash actions can lead to misfortune, and a careful reassessment of the situation is needed.",
    fourth: "This line suggests that there may be an opportunity for reconciliation. It advises openness to dialogue and the possibility of resolving conflicts through understanding.",
    fifth: "The fifth line indicates that one’s integrity and moral character will lead to respect and admiration from others, helping to resolve conflicts.",
    sixth: "The sixth line warns that the conflict may be irresolvable at this time. It advises withdrawing from the situation to avoid further loss or harm.",
    all: "",
},
{
    name: '師 SHI',
    composition: '010000',
    aspect: 'COLLECTIVE FORCE',
    guidance: 'Collective force requires correct persistence. With a storng leader there will be good fortune. Then there will be no mistake.',
    wisdom: 'In the midst of the receptive (earth) is the profound (water) forming the condition for Collective Force. An enlightened person, therefore, is generous toward the people and finds strength in their numbers.',
    art: '',
    upper: 2,
    lower: 5,
    first: "The first line suggests the need for proper preparation and organization. It’s a time to ensure that the fundamentals are strong before proceeding.",
    second: "This line indicates that with discipline and perseverance, small but steady progress can be made. It’s important to stay focused on the goal.",
    third: "The third line warns against potential pitfalls in the pursuit of goals. It advises reassessing strategies and ensuring that the approach is morally sound and well-planned.",
    fourth: "This line suggests that unity and cooperation are key. By working harmoniously with others and sharing the burden, challenges can be overcome.",
    fifth: "The fifth line indicates that strong leadership is required. It suggests that by taking responsibility and acting decisively, success can be achieved.",
    sixth: "The sixth line warns against overreaching or extending beyond one's capabilities. It advises knowing when it is time to retreat and avoid unnecessary risks.",
    all: "",
},
{
    name: '比 BI',
    composition: '000010',
    aspect: 'UNITY',
    guidance: 'Unity brings good fortune. Further consultation with the oracle will dviine the durability and correctness of the goal; then there will be no mistake. Those who are uncertain should return to the plan; those who procrastinate will meet with misfortune.',
    wisdom: 'Above the receptive (earth) is the profound (water) forming the condition for Unity. The ancient rulers, therefore, proposed worldwide awareness and cultivated personal relationships with the various leaders',
    art: '',
    upper: 5,
    lower: 2,
    first: "The first line suggests that forming alliances and seeking unity with like-minded individuals will lead to progress and success.",
    second: "This line indicates that sincerity and a genuine heart will attract others. True unity comes from shared values and mutual trust.",
    third: "The third line warns against superficial connections based on selfish motives. It advises reassessing relationships and focusing on building genuine bonds.",
    fourth: "This line suggests that in times of uncertainty, sticking to one’s principles and being true to oneself will attract the right kind of support.",
    fifth: "The fifth line indicates that strong, supportive relationships are the foundation for success. It advises nurturing these bonds and leading with integrity and virtue.",
    sixth: "The sixth line warns against misplaced loyalty or staying in a situation where the unity has been lost. It advises reevaluating one’s connections and moving on if necessary.",
    all: "",
},
{
    name: '小畜 XIAO XU',
    composition: '111011',
    aspect: 'RESTRAINED',
    guidance: 'Restrained will bring progress. Dense clouds, but no rain is seen from our border on the west (satisfaction)',
    wisdom: 'The gradual (wind) moves about the firm (heaven) forming the condition for Restrained. An englihtened person, therefore, must conceal even his virtuous conduct.',
    art: '',
    upper: 4,
    lower: 8,
    first: "The first line suggests that while progress is slow, persistence and patience will eventually lead to success. It's a time to attend to small details and proceed cautiously.",
    second: "This line indicates that one's sincere efforts are noticed and will eventually be rewarded. It encourages staying true to one's path despite current limitations.",
    third: "The third line warns against trying to force progress. It suggests that one should be patient and wait for the right moment to act.",
    fourth: "This line suggests that a change in approach may be necessary. It advises reassessing the situation and adapting as needed to overcome obstacles.",
    fifth: "The fifth line indicates that persistence and integrity will lead to success. It suggests that one's efforts will be recognized and rewarded.",
    sixth: "The sixth line warns that further efforts may be futile at this time. It advises recognizing when to stop and wait for more favorable conditions.",
    all: "",
},
{
    name: '履 LU',
    composition: '110111',
    aspect: 'CONDUCT',
    guidance: 'Conduct. Treading up on the tail of the tiger; it does not bite. There will be progress.',
    wisdom: 'Firmness (heaven) is above and excess (lake) is below forming the condition for Conduct. An englihtened person, therefore, discriminates between superior and inferior, and the thereby stabilizes public opinion',
    art: '',
    upper: 3,
    lower: 4,
    first: "The first line suggests proceeding with caution and respect. It’s a time to be mindful of one's actions and their potential consequences.",
    second: "This line indicates that by acting correctly and with confidence, one will make steady progress. It encourages integrity and steadiness in one's path.",
    third: "The third line warns against acting rashly or stepping into danger without awareness. It suggests the need for caution and careful consideration of one's actions.",
    fourth: "This line suggests that despite potential dangers, one has the strength and ability to navigate challenges successfully. It encourages courage and resilience.",
    fifth: "The fifth line indicates that through humility and respect, one will navigate through challenges successfully. It encourages maintaining virtue even in difficult times.",
    sixth: "The sixth line warns against overconfidence or acting without regard for others. It advises reassessing one's approach to ensure it is just and respectful.",
    all: "",
},
{
    name: '泰 TAI',
    composition: '111000',
    aspect: 'PROSPERING',
    guidance: 'Prospering. The inferior is going. The superior is coming. There will be good fortune and progres.',
    wisdom: 'A direct exchange between the creative (heaven) and the receptive (earth) forms the condition for Prospering. A true leader, therefore, can benefit from the harmony between heaven and earth. he is able to organize and interpret cosmic events and, in doing so, help others.',
    art: '',
    upper: 2,
    lower: 4,
    first: "The first line suggests proceeding with caution and respect. It’s a time to be mindful of one's actions and their potential consequences.",
    second: "This line indicates that by acting correctly and with confidence, one will make steady progress. It encourages integrity and steadiness in one's path.",
    third: "The third line warns against acting rashly or stepping into danger without awareness. It suggests the need for caution and careful consideration of one's actions.",
    fourth: "This line suggests that despite potential dangers, one has the strength and ability to navigate challenges successfully. It encourages courage and resilience.",
    fifth: "The fifth line indicates that through humility and respect, one will navigate through challenges successfully. It encourages maintaining virtue even in difficult times.",
    sixth: "The sixth line warns against overconfidence or acting without regard for others. It advises reassessing one's approach to ensure it is just and respectful.",
    all: "",
},

{
    name: '否 PI',
    composition: '000111',
    aspect: 'STAGNATION',
    guidance: 'Stagnation is brought about by inferior persons. There exists no advantage -- even to persons of exceptional character and virtue. The superior is going; the inferior is coming.',
    wisdom: 'The creative (heaven) and the receptive (earth) do not intersect in forming the condition for Stagnation. An enlightened person, therefore, is reserved in his behavior and in that way avoids misfortune. He refuses to be honored with riches.',
    art: '',
    upper: 4,
    lower: 2,
    first: "The first line suggests that despite the stagnation, maintaining one's integrity and inner strength will eventually lead to improvement.",
    second: "This line indicates that in times of stagnation, small actions aligned with one's values can still make a positive impact. It's important to stay true to oneself.",
    third: "The third line warns against giving in to negativity or resorting to unethical behavior during difficult times. It emphasizes the importance of maintaining one's principles.",
    fourth: "This line suggests that a period of stagnation is coming to an end. It advises readiness to act and seize new opportunities as they arise.",
    fifth: "The fifth line indicates that one's positive and principled approach will attract support and lead to a reversal of the negative situation.",
    sixth: "The sixth line warns that the period of stagnation may persist for a while longer. It advises patience and maintaining one's integrity until the situation improves.",
    all: "",
},
{
    name: '同人 TONG REN',
    composition: '101111',
    aspect: 'COMMUNITY',
    guidance: 'Community in the open brings progress. It is advantageous to experience the collective flow. There is further advantage in correct persistence.',
    wisdom: 'The strong (heaven) together with the dependent (fire) form the condition for Community. An enlightened person, therefore, recognizes his fellow mans place in the outside world',
    art: '',
    upper: 4,
    lower: 1,
    first: "The first line suggests that while seeking harmony and unity, it's important to remain true to one's principles and not compromise one's integrity.",
    second: "This line indicates that sincere efforts to build alliances and understanding will lead to trust and mutual respect among others.",
    third: "The third line warns against the potential for misunderstanding or conflict when seeking unity. It advises clear communication and genuine intentions.",
    fourth: "This line suggests that alliances and friendships formed will be beneficial and lead to mutual success. It encourages openness and collaboration.",
    fifth: "The fifth line indicates that one's positive influence and leadership will attract loyalty and support, fostering a harmonious environment.",
    sixth: "The sixth line warns that seeking superficial unity or neglecting genuine connections can lead to isolation. It advises focusing on authentic relationships.",
    all: "",
},
{
    name: '大有 DA YOU',
    composition: '111101',
    aspect: 'SOVEREIGNTY',
    guidance: 'Sovereignty brings exceptional progress.',
    wisdom: 'Intelligence (fire) is within the strong (heaven) forming the condition for Sovereignty. An enlightened person represses evil influences by making obvious that which is good. He aligns himself with the unfolding destiny of the cosmos.',
    art: '',
    upper: 1,
    lower: 4,
    first: "The first line suggests that modesty and a willingness to share one's wealth or success with others will lead to further prosperity and respect.",
    second: "This line indicates that one's current position and resources are stable and should be used wisely. It encourages responsible and ethical use of wealth.",
    third: "The third line warns against arrogance or using one's resources unwisely. It emphasizes the importance of humility and consideration for others.",
    fourth: "This line suggests that generosity and a willingness to support others will not only benefit them but also enhance one's own standing and success.",
    fifth: "The fifth line indicates a position of great influence and wealth. It advises using this power benevolently and maintaining an attitude of gratitude and humility.",
    sixth: "The sixth line warns against the dangers of excessive pride or greed. It advises maintaining a balanced perspective and staying grounded despite one's wealth.",
    all: "",
},
{
    name: '謙 QIAN',
    composition: '001000',
    aspect: 'MODERATION',
    guidance: 'Moderation brings progress. An englightened person carries things out to completion.',
    wisdom: 'The tranquil (mountain) is in the midst of the receiptive (earth) forming the conditions for Moderation. An enlightend person, therefore, reduces the excessive and increases the insufficient. He weights the outside world and bring about equality.',
    art: '',
    upper: 2,
    lower: 6,
    first: "The first line suggests that modesty in one's position will lead to advancement and good fortune. It's important to stay humble and be true to oneself.",
    second: "This line indicates that practicing modesty, even in a high position, will earn respect and support from others, leading to stability and success.",
    third: "The third line warns against pretending to be modest while harboring pride. It advises genuine humility to ensure progress and avoid misfortune.",
    fourth: "This line suggests that maintaining modesty and integrity, even when faced with difficult tasks or situations, will lead to recognition and respect.",
    fifth: "The fifth line indicates that sincere modesty, without ulterior motives, will attract good fortune and the support of others.",
    sixth: "The sixth line warns that excessive modesty or self-deprecation can lead to missed opportunities. It advises finding a balance between humility and recognizing one's worth.",
    all: "",
},
{
    name: '豫 YU',
    composition: '000100',
    aspect: 'HARMONIZE',
    guidance: 'Harmonize. It is advantageous to develop supporters and emerge as a master.',
    wisdom: 'Excitement (thunder) comes resounding out of the receptive (earth) forming the condition for Harmonize. The ancient rulers composed music that upheld virtuous ideals as a sacrifice to the Ultimate Plan. They were worthy of their originators.',
    art: '',
    upper: 7,
    lower: 2,
    first: "The first line suggests that enthusiasm and confidence are just beginning to build. It's a time to plan carefully and not rush into action.",
    second: "This line indicates that sincere enthusiasm will be contagious and attract support from others, leading to progress and success.",
    third: "The third line warns against unfounded enthusiasm or overconfidence. It advises ensuring that one's plans are solid and realistic before proceeding.",
    fourth: "This line suggests that a time of great enthusiasm and energy is at hand. It encourages taking decisive action to seize the moment and achieve one's goals.",
    fifth: "The fifth line indicates that one's enthusiasm and leadership will inspire others and lead to collective success. It encourages leading with sincerity and passion.",
    sixth: "The sixth line warns against the potential for enthusiasm to wane or become misguided. It advises reassessing one's goals and motivations to stay on track.",
    all: "",
},
{
    name: "Suí (隨)", // Name in Pinyin then Hanzi
    composition: "100110", // results of coin flips building left -> right bottom -> top
    aspect: "ADAPT",
    guidance: "Suí suggests the importance of following a path or a leader that aligns with one's values. It implies a period of learning and adapting, where observing and understanding the actions of others can lead to progress.",
    wisdom: "True leadership is achieved through inspiration and example, not force. Adaptability and openness to change pave the way for success.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Gǔ (蠱)",
    composition: "011001",
    aspect: "REPAIR",
    guidance: "Gǔ represents the need to correct past mistakes and heal from their consequences. It emphasizes the importance of addressing problems that have been inherited or neglected.",
    wisdom: "Rectifying faults and addressing problems at their root brings renewal and progress.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Lín (臨)",
    composition: "110000",
    aspect: "PROMOTION",
    guidance: "Lín signifies a time of gradual progress and advancement. It suggests drawing near with care and correctness.",
    wisdom: "Success comes from a thoughtful approach and a respectful attitude towards those around you.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Guan (觀)",
    composition: "000011",
    aspect: "CONTEMPLATION",
    guidance: "Guan is about observation and gaining perspective. It advises taking a step back to better understand the broader context of a situation.",
    wisdom: "True understanding comes from observing not just with the eyes, but with the heart.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Shi He (噬嗑)",
    composition: "100101",
    aspect: "REFORM",
    guidance: "Shi He symbolizes the need to address problems or obstacles directly and decisively. It suggests confronting issues head-on to resolve them, much like biting through a tough obstacle.",
    wisdom: "Justice and clarity arise from addressing issues with directness and honesty. Decisive action, when guided by fairness and truth, leads to resolution.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Bì (賁)",
    composition: "101001",
    aspect: "GRACE",
    guidance: "Bì represents the concept of grace, beauty, and elegance, emphasizing the importance of outer appearances and their impact on success. It suggests that aesthetic considerations can have a significant influence on how things are perceived and received.",
    wisdom: "True beauty and grace are more than superficial; they arise from inner truth and sincerity. Outer elegance should reflect inner goodness.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Bō (剝)",
    composition: "000001",
    aspect: "DETERIORATION",
    guidance: "Bō symbolizes a time of decline or disintegration, where structures and relationships may be breaking down. It suggests a period of letting go, and the importance of recognizing when something is no longer sustainable or beneficial.",
    wisdom: "In times of decline, resilience and integrity become crucial. Accepting the natural end of things allows for new growth and opportunities.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Fù (復)",
    composition: "100000",
    aspect: "RETURN",
    guidance: "Fù signifies a return to beginnings or a turning point. It indicates a time of renewal and recovery, where past mistakes can be rectified, and one can get back on the right path. It's a reminder of the natural cycles of growth and decline, and the importance of returning to one's roots.",
    wisdom: "True progress often requires a return to the foundation of things. Reflecting on the past and learning from it is essential for moving forward effectively.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Wú Wàng (无妄)",
    composition: "100111",
    aspect: "INNOCENCE",
    guidance: "Wú Wàng represents the principle of innocence, spontaneity, and naturalness. It suggests that success comes from acting in a straightforward and unpretentious manner, without hidden agendas or manipulative intentions. Emphasizes the importance of being true to one’s nature and responding spontaneously to life's situations.",
    wisdom: "The greatest strength lies in simplicity and honesty. Acting without false pretense or ulterior motives aligns one with the natural order.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Dà Chù (大畜)",
    composition: "111001",
    aspect: "POTENTIAL ENERGY",
    guidance: "Dà Chù represents the concept of accumulating strength and exercising restraint. It suggests a period of building up resources and capabilities, while also advising against acting prematurely. Emphasizes the importance of patience, discipline, and the strategic use of power.",
    wisdom: "True power and effectiveness come from restraint and the judicious use of force. By cultivating inner strength and wisdom, one can act decisively at the right moment.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Yí (颐)",
    composition: "100001",
    aspect: "NOURISHING",
    guidance: "Yí symbolizes nourishment, not just in the physical sense, but also mentally and spiritually. It emphasizes the importance of being mindful of what one 'feeds' oneself in terms of thoughts, beliefs, and influences. It advises care in choosing what sustains and forms you, underscoring the significance of ethical and nourishing influences.",
    wisdom: "True sustenance comes not only from the food we eat but from the ideas we consume and the moral company we keep. Nourishing the right elements within us leads to a wholesome life.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Dà Guò (大过)",
    composition: "011110",
    aspect: "CRITICAL MASS",
    guidance: "Dà Guò speaks to situations of great excess or imbalance. It suggests a time when structures or situations are under strain due to being overstretched or overloaded. This hexagram advises recognizing the unsustainable nature of such conditions and the need for change or realignment.",
    wisdom: "Endurance in the face of imbalance is not always virtue. Recognizing the need to reduce excess and restore balance is crucial for long-term stability and success.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Kǎn (坎)",
    composition: "010010",
    aspect: "DANGER",
    guidance: "Kǎn represents challenging or dangerous situations, often symbolized by water in a gorge. It suggests enduring difficult times with perseverance and inner strength. The hexagram advises caution, steadiness, and resilience in the face of adversity.",
    wisdom: "In the face of danger and uncertainty, maintaining a calm and steadfast heart leads to survival and success. Courage and resilience in trials are sources of true power.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Lí (離)",
    composition: "101101",
    aspect: "SYNERGY",
    guidance: "Lí symbolizes light, clarity, and dependence. As fire clings to its fuel, this hexagram suggests clinging to what is bright and good. It emphasizes the need for clear understanding and the pursuit of enlightenment. The hexagram advises seeking clarity in all endeavors and illuminating one's path with wisdom.",
    wisdom: "Like fire, enlightenment and clarity bring light to darkness and guide the way. Adhering to what is true and good, and illuminating one's life with insight and knowledge, is key to progress.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Xián (咸)",
    composition: "001110",
    aspect: "ATRACTION",
    guidance: "Xián represents the theme of influence and attraction, particularly in the context of relationships and interactions. It suggests the importance of mutual attraction and responsiveness. The hexagram advises acting with sensitivity and awareness of others, highlighting the power of gentle persuasion and sincere intentions in creating harmonious connections.",
    wisdom: "True influence arises from genuine connection and empathy, not force. Creating relationships based on mutual respect and understanding leads to positive outcomes.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Héng (恒)",
    composition: "011100",
    aspect: "CONTINUING",
    guidance: "Héng speaks to the concept of duration and perseverance. It emphasizes the importance of steadiness and consistency in maintaining successful relationships, endeavors, and principles. The hexagram advises on the value of enduring commitment and the steady cultivation of practices and connections that are sustainable over time.",
    wisdom: "Lasting success and harmony come from consistency and reliability. By maintaining a steady course and upholding one's commitments, enduring progress is achieved.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Dùn (遯)",
    composition: "001111",
    aspect: "RETREAT",
    guidance: "Dùn symbolizes the strategic necessity of retreat or withdrawal. It advises recognizing when to disengage from adverse situations or conflicts. The emphasis is on the wisdom of stepping back when faced with overwhelming odds or unfavorable conditions, not as a sign of defeat, but as a tactful maneuver to conserve strength and reassess strategies.",
    wisdom: "True strength sometimes lies in knowing when to retreat. Disengagement from a no-win situation allows for preservation of resources and preparation for future opportunities.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Dà Zhuàng (大壯)",
    composition: "111100",
    aspect: "GREAT POWER",
    guidance: "Dà Zhuàng represents great power and strength. It indicates a time when one's influence is at its peak. The hexagram advises using this power responsibly and with restraint. It cautions against overreaching or using strength to dominate others, emphasizing the importance of channeling one's energy in a positive and constructive manner.",
    wisdom: "True power is most effective when used with wisdom and restraint. The strength should be directed towards noble goals, not for mere domination or ego.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Jìn (晋)",
    composition: "000101",
    aspect: "PROGRESS",
    guidance: "Jìn symbolizes progress and advancement. It indicates a time of improvement and forward movement in various aspects of life. The hexagram advises taking advantage of favorable conditions to advance one's goals and aspirations. It suggests that this is a time when efforts will be recognized and rewarded, and encourages active pursuit of success.",
    wisdom: "True progress is achieved through consistent effort and taking advantage of opportune moments. Recognition and success come to those who actively seek growth and improvement.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Míng Yí (明夷)",
    composition: "101000",
    aspect: "DARK REGIME",
    guidance: "Míng Yí symbolizes a period of adversity or decline, where light and clarity are obscured. It suggests a time of keeping a low profile and protecting one’s inner light during challenging circumstances. The hexagram advises caution and discretion, emphasizing the importance of maintaining inner strength and integrity even when external conditions are unfavorable.",
    wisdom: "True resilience is maintaining hope and integrity in times of darkness. By safeguarding one's values and inner light, one can endure and emerge stronger from periods of hardship.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Jiā Rén (家人)",
    composition: "101011",
    aspect: "FAMILY",
    guidance: "Jiā Rén focuses on the dynamics and importance of the family unit. It suggests the need for clear roles, mutual respect, and proper conduct within the family to ensure harmony and stability. The hexagram emphasizes the value of nurturing and supporting each other, creating a strong foundation for both the family and society.",
    wisdom: "True strength of a society lies in the health of its family units. Harmony at home extends to harmony in the larger community, emphasizing the importance of strong, supportive relationships.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Kuí (睽)",
    composition: "110101",
    aspect: "CONTRADICTION",
    guidance: "Kuí represents a situation of contrast, misunderstanding, or opposition. It suggests a time when differing views or interests create a divide. The hexagram encourages finding common ground and understanding the value of diverse perspectives. It advises against allowing differences to lead to conflict, instead, suggesting the need for communication and an open-minded approach to resolve disagreements.",
    wisdom: "True harmony often arises from recognizing and respecting differences. Bridging gaps and seeking mutual understanding are key to overcoming opposition and achieving balance.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Jiǎn (蹇)",
    composition: "001010",
    aspect: "OBSTACLES",
    guidance: "Jiǎn symbolizes a period of obstacles or impediments. It suggests facing difficulties or barriers that hinder progress. The hexagram advises patience and caution, recommending a reevaluation of the current approach or path. It encourages seeking alternative solutions or getting help from others, emphasizing the importance of adapting to challenges rather than confronting them head-on.",
    wisdom: "True wisdom lies in recognizing when the path is obstructed and seeking alternative routes. Overcoming obstacles often requires flexibility, patience, and sometimes a strategic retreat.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Xiè (解)",
    composition: "010100",
    aspect: "LIBERATION",
    guidance: "Xiè represents the concept of relief and liberation from hardship or entanglements. It suggests a period of release from tensions, obstacles, or difficulties, marking a time of recovery and easing of pressures. The hexagram advises taking advantage of this time to resolve outstanding issues and to move forward with a sense of renewal.",
    wisdom: "True liberation comes from resolving what binds us and learning from past challenges. Release from difficulties offers a chance for growth and a fresh start.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Sǔn (損)",
    composition: "110001",
    aspect: "DECLINE",
    guidance: "Sǔn symbolizes the concept of decrease or reduction. It suggests a time of conserving resources and simplifying one’s life. The hexagram advises focusing on what is essential and eliminating excesses. It emphasizes the value of modesty and restraint, and how cutting back in certain areas can lead to growth and improvement in others.",
    wisdom: "True progress sometimes requires sacrifice and reduction. By letting go of the non-essential, one can focus on what truly matters and achieve greater harmony and balance.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Yì (益)",
    composition: "100011",
    aspect: "BENEFIT",
    guidance: "Yì represents the idea of increase, growth, and expansion. It suggests a period where efforts are rewarded and progress is made. The hexagram advises seizing opportunities for advancement and sharing the benefits of success with others. It emphasizes the importance of generosity and using one’s gains to support and uplift those around you.",
    wisdom: "True abundance comes from not only personal gain but also from enriching others. Prosperity is most meaningful when shared and used to create mutual benefit.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Guài (夬)",
    composition: "111110",
    aspect: "RESOLUTION",
    guidance: "Guài symbolizes a decisive breakthrough, marking a time when one must take firm action to resolve a situation. It suggests the importance of assertiveness and clarity in addressing problems or obstacles. The hexagram advises making one's intentions clear and taking decisive steps to overcome difficulties, emphasizing the need for strength and determination in resolving uncertainties or conflicts.",
    wisdom: "True resolution comes from taking decisive and firm action in critical moments. A clear, forceful approach is sometimes necessary to overcome challenges and assert one's position.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Gòu (姤)",
    composition: "011111",
    aspect: "TEMPTATION",
    guidance: "Gòu represents the theme of encounter, often signifying an unexpected meeting or the emergence of a powerful influence. It advises caution and awareness in the face of new developments or people entering one's life. The hexagram suggests examining the nature of these encounters and their potential impact, whether positive or challenging, and preparing to respond appropriately.",
    wisdom: "True insight comes from recognizing the significance of new encounters and understanding their potential influence on our lives. It is important to stay true to one's principles while adapting to new situations.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Cuì (萃)",
    composition: "000110",
    aspect: "ASSEMBLY",
    guidance: "Cuì symbolizes the act of gathering together or assembling. It suggests a time of coming together for a common purpose or goal. The hexagram advises creating unity and harmony among diverse elements, emphasizing the importance of community, cooperation, and collective efforts. It points to the strength found in unity and the power of collective goals over individual ambitions.",
    wisdom: "True strength lies in unity and cooperation. Bringing people together for a shared purpose leads to greater achievementsand success than working alone. Collaboration and unity are essential for reaching common goals.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Shēng (升)",
    composition: "011000",
    aspect: "ADVANCEMENT",
    guidance: "Shēng represents the concept of upward movement and progress. It symbolizes steady and gradual advancement, like plants growing upwards. The hexagram suggests working diligently and persistently towards one's goals, emphasizing the importance of a strong foundation and consistent effort. It advises patience and perseverance, as success often comes gradually.",
    wisdom: "True progress is often slow and requires steady, continuous effort. Like a plant reaching towards the sun, growth and success are achieved through persistent effort and resilience.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Kùn (困)",
    composition: "010110",
    aspect: "ADVERSITY",
    guidance: "Kùn represents a state of hardship or confinement, symbolizing a period where one feels restricted or challenged by external circumstances. The hexagram advises finding inner strength and wisdom to overcome these difficulties. It suggests that patience, resilience, and a clear understanding of one's situation are key to navigating through times of adversity.",
    wisdom: "True strength emerges in times of challenge. Enduring difficult situations with patience and maintaining moral integrity leads to eventual liberation and growth.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Jǐng (井)",
    composition: "011010",
    aspect: "THE SOURCE",
    guidance: "Jǐng symbolizes the well, representing a source of nourishment and replenishment. It suggests a constant and reliable resource that sustains and supports. The hexagram advises maintaining and valuing the resources and support systems that are consistently available, emphasizing the importance of communal benefits and shared resources. It also highlights the need for care and maintenance to ensure these resources remain beneficial to all.",
    wisdom: "True sustainability lies in the careful management and preservation of resources. Like a well that serves a community, our actions should aim to support and sustain the collective good.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Gé (革)",
    composition: "101110",
    aspect: "CHANGE",
    guidance: "Gé symbolizes a period of transformation and change, akin to a revolution. It suggests a time when old structures or ways of thinking are being overthrown in favor of new ones. The hexagram advises readiness for change and the importance of adapting to new conditions. It emphasizes the need for clear vision and decisive action when pursuing significant changes, whether personal or communal.",
    wisdom: "True transformation requires a clear vision and a commitment to change. Embracing new ideas and approaches leads to progress and rejuvenation.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Dǐng (鼎)",
    composition: "011101",
    aspect: "COSMIC ORDER",
    guidance: "Dǐng represents the cauldron, symbolizing nourishment and transformation. It suggests the importance of creating a supportive environment for growth and development. The hexagram emphasizes the role of nurturing, care, and the sustenance of resources, whether material, spiritual, or social. It advises taking responsibility in providing for others and in the cultivation of positive change and development.",
    wisdom: "True nourishment comes from providing support and sustenance to others as well as oneself. Like a cauldron that transforms ingredients into nourishing food, we can transform resources into something valuable and sustaining.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Zhèn (震)",
    composition: "100100",
    aspect: "THUNDERCLAP",
    guidance: "Zhèn symbolizes shock or thunder, representing sudden, powerful, and unexpected change. It suggests a time of awakening and the jolting of complacency. The hexagram advises being alert and prepared to respond swiftly to unforeseen events. It emphasizes the need for resilience and adaptability in the face of surprises or upheavals.",
    wisdom: "True growth often comes from unexpected challenges. Being adaptable and responsive in the face of sudden changes leads to learning and development.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Gèn (艮)",
    composition: "001001",
    aspect: "MEDITATION",
    guidance: "Gèn represents stillness and immovability, like a mountain. It suggests a time for pausing, reflecting, and cultivating inner strength and stability. The hexagram advises finding peace and tranquility within oneself and stresses the importance of a calm, centered approach to life's challenges. It emphasizes the need for meditation, rest, and setting firm boundaries.",
    wisdom: "True strength and progress come from inner stillness and reflection. By being grounded and centered, one can make wise decisions and withstand life's turbulence.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Jiàn (漸)",
    composition: "001011",
    aspect: "DEVELOPING",
    guidance: "Jiàn symbolizes gradual progress and development, akin to the slow growth of a tree. It suggests a period of steady, incremental advancement where patience and persistence are key. The hexagram advises taking things step by step and not rushing the natural course of events. It emphasizes the importance of laying down a solid foundation and allowing things to mature at their own pace.",
    wisdom: "True achievement is often the result of gradual and persistent effort. Patience and perseverance lead to solid and lasting progress.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",
},
{
    name: "Guī Mèi (歸妹)", // Name in Pinyin and Hanzi
    composition: "110100",   // Initialized as a blank string
    aspect: "SUBORDINATE",
    guidance: "Guī Mèi represents the concept of marriage or union, often suggesting a subordinate or secondary position. It symbolizes a situation where adaptation and compromise are necessary. The hexagram advises understanding one's role and adapting to circumstances with grace and flexibility. It highlights the importance of patience and the careful navigation of complex interpersonal dynamics.",
    wisdom: "True harmony in relationships often requires understanding, adaptability, and patience. Recognizing and respecting the roles and dynamics in any union leads to a balanced and respectful partnership.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "", // Initialized as a blank string
},
{
    name: "Fēng (豐)", // Name in Pinyin and Hanzi
    composition: "101100",   // Initialized as a blank string
    aspect: "ZENITH",
    guidance: "Fēng symbolizes a period of abundance and fullness. It suggests a time of great potential and success, where resources and opportunities are plentiful. The hexagram advises recognizing and making the most of this prosperous phase, while also being mindful of the inherent challenges that come with periods of great excess. It emphasizes the need for moderation and foresight to sustain this abundance over time.",
    wisdom: "True prosperity requires not just enjoying abundance, but also managing it wisely. Being prepared for future fluctuations and maintaining balance ensures long-term success.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Lǚ (旅)", // Name in Pinyin and Hanzi
    composition: "001101",   // Initialized as a blank string
    aspect: "JOURNEY",
    guidance: "Lǚ represents the wanderer or traveler, suggesting a journey or a transient phase. It emphasizes the importance of adaptability, self-reliance, and maintaining a sense of humility and caution in unfamiliar circumstances. The hexagram advises taking care in one's conduct and decisions while away from home or in changing situations, highlighting the need for awareness and discretion.",
    wisdom: "True wisdom in travel lies in adaptability and the ability to maintain integrity and careful judgment, even in unfamiliar or challenging environments.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Xiù (巽)", // Name in Pinyin and Hanzi
    composition: "011011",   // Initialized as a blank string
    aspect: "GENTLE WIND",
    guidance: "Xiù represents the gentle, like the wind. It symbolizes the power of flexibility and receptivity. The hexagram advises adopting a soft, yielding approach, especially in situations where resistance may be counterproductive. It emphasizes the value of adaptability and the ability to flow with changing circumstances, like the wind that can move around obstacles.",
    wisdom: "True strength often comes from a gentle and flexible approach. The ability to adapt and flow, like the wind, can overcome obstacles and achieve progress.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Duì (兌)", // Name in Pinyin and Hanzi
    composition: "110110",   // Initialized as a blank string
    aspect: "ENCOURAGING",
    guidance: "Duì symbolizes joy and enthusiasm, often associated with a joyful gathering around a lake. It suggests a time of celebration, harmony, and mutual support. The hexagram advises fostering positive relationships, embracing joy, and spreading cheerfulness. It emphasizes the importance of connecting with others in a spirit of unity and shared happiness.",
    wisdom: "True happiness comes from sharing joy and celebrating with others. The ability to spread positivity and create harmony enhances the quality of life for all.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Huàn (渙)", // Name in Pinyin and Hanzi
    composition: "010011",   // Initialized as a blank string
    aspect: "DISSOLUTION",
    guidance: "Huàn represents a time of dispersion or dissolution, suggesting the breaking apart of old structures or relationships. It advises accepting change and not resisting the natural flow of events. The hexagram emphasizes the need to let go of attachments and to adapt to new circumstances. It also highlights the potential for new beginnings after dissolution.",
    wisdom: "True transformation often requires letting go of the old to make way for the new. Embracing change and being open to new possibilities lead to growth and renewal.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Jié (節)", // Name in Pinyin and Hanzi
    composition: "110010",   // Initialized as a blank string
    aspect: "LIMITATIONS",
    guidance: "Jié represents limitation or articulation, suggesting the need for restraint and moderation. It advises setting boundaries and being clear in communication. The hexagram emphasizes the importance of discipline and focus, recognizing that limits can lead to greater creativity and effectiveness. It encourages defining one's goals and adhering to them with diligence.",
    wisdom: "True accomplishment often comes from defining boundaries and adhering to them with discipline. Constraints can lead to greater clarity and success in one's endeavors.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Zhōng Fú (中孚)", // Name in Pinyin and Hanzi
    composition: "110011",   // Initialized as a blank string
    aspect: "INSIGHT",
    guidance: "Zhōng Fú symbolizes inner truth and sincerity, emphasizing the importance of honest communication and inner alignment. It advises being truthful in words and actions and avoiding deception or hypocrisy. The hexagram highlights the power of genuine sincerity in building trust and fostering harmonious relationships.",
    wisdom: "True trust and harmony are built on sincere and honest communication. Being genuine and true to oneself and others leads to meaningful connections and deep relationships.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Xiǎo Guò (小過)", // Name in Pinyin and Hanzi
    composition: "001100",   // Initialized as a blank string
    aspect: "CONSCIENTIOUSNESS",
    guidance: "Xiǎo Guò represents the preponderance of the small or the principle that small things can exceed the large. It suggests paying attention to the details and not underestimating the power of small actions or influences. The hexagram advises being cautious and attentive to minor matters, as they can have significant effects.",
    wisdom: "True success often comes from being attentive to small details and recognizing their potential impact. Small actions and influences can lead to significant outcomes.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Jì Jì (既濟)", // Name in Pinyin and Hanzi
    composition: "101010",   // Initialized as a blank string
    aspect: "AFTER THE END",
    guidance: "Jì Jì symbolizes a state of completion and fulfillment, suggesting the achievement of goals and the realization of intentions. It advises recognizing and celebrating success while also preparing for what comes next. The hexagram emphasizes the importance of closure and proper conclusion.",
    wisdom: "True accomplishment requires acknowledging and celebrating completion while also preparing for new beginnings. Closure and fulfillment pave the way for future success.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
{
    name: "Wèi Jì (未濟)", // Name in Pinyin and Hanzi
    composition: "010101",   // Initialized as a blank string
    aspect: "BEFORE THE END",
    guidance: "Wèi Jì symbolizes a state before completion, suggesting that goals are not yet fully realized. It advises being cautious and patient while working towards completion. The hexagram emphasizes the need for perseverance and attention to detail in order to bring a project or situation to a successful conclusion.",
    wisdom: "True success often requires patience and careful attention to details. Being diligent and focused on completing tasks leads to the realization of goals.",
    art: "",
    upper:,
    lower:,
    first:,
    second:,
    third:,
    fourth:,
    fifth:,
    sixth:,
    all: "",            // Initialized as a blank string
},
]
module.exports = hex_seeds
